identity_providers:
  oidc:
    hmac_secret: '{{ env "AUTHELIA_OIDC_HMAC_SECRET" }}'
    jwks:
      - key: {{ secret "/config/oidc.pem" | mindent 10 "|" | msquote }}
    clients:
      - client_id: 'immich'
        client_name: 'Immich'
        client_secret: '{{ env "IMMICH_OIDC_SECRET" }}'
        redirect_uris:
          - 'https://photos.{{ env "TS_DOMAIN" }}/auth/login'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        userinfo_signed_response_alg: 'none'

      - client_id: 'mealie'
        client_name: 'Mealie'
        client_secret: '{{ env "MEALIE_OIDC_SECRET" }}'
        redirect_uris:
          - 'https://recipes.{{ env "TS_DOMAIN" }}/login'
        scopes:
          - 'openid'
          - 'email'
          - 'profile'
        userinfo_signed_response_alg: 'none'