services:
  shelfmark:
    container_name: shelfmark
    image: calibrain/shelfmark:latest
    restart: always
    env_file: ../../.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
    volumes:
      - ${SHELFMARK_CONFIG}:/config
      - ${BOOKS_PATH}:/library
      - ${BOOKS_INGEST}:/watch
    command: ["shelfmark", "watch", "--source", "/watch", "--destination", "/library", "--config", "/config/config.yml", "--remove"]
    networks:
      - proxy

  calibre-web-automated:
    container_name: calibre-web-automated
    image: crocodilestick/calibre-web-automated:latest
    restart: always
    env_file: ../../.env
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
    volumes:
      - ${CALIBREWEB_CONFIG}:/config
      - ${BOOKS_PATH}:/calibre-library
      - ${BOOKS_INGEST}:/cwa-book-ingest
    networks:
      - proxy
