services:
  shelfmark:
    container_name: shelfmark
    image: ghcr.io/calibrain/shelfmark:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
    volumes:
      - ${DATA_DIR}/shelfmark:/config
      - ${DATA_DIR}/books:/books
    networks:
      - proxy

  kavita:
    container_name: kavita
    image: lscr.io/linuxserver/kavita:latest
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TIMEZONE}
    volumes:
      - ${DATA_DIR}/kavita:/config
      - ${DATA_DIR}/books:/books:ro
      - ${DATA_DIR}/comics:/comics:ro
    networks:
      - proxy
