- Apps:
    - Immich:
        icon: immich
        href: https://photos.{{HOMEPAGE_VAR_DOMAIN}}
        description: Photos
        server: my-docker
        container: immich-server
    - Mealie:
        icon: mealie
        href: https://recipes.{{HOMEPAGE_VAR_DOMAIN}}
        description: Recipes
        server: my-docker
        container: mealie
    - Calibre-Web:
        icon: calibre-web
        href: https://calibre.{{HOMEPAGE_VAR_DOMAIN}}
        description: Book library
        server: my-docker
        container: calibre-web

- Media Automation:
    - qBittorrent:
        icon: qbittorrent
        href: https://downloads.{{HOMEPAGE_VAR_DOMAIN}}
        description: Downloads
        server: my-docker
        container: qbittorrent
    - Prowlarr:
        icon: prowlarr
        href: https://indexer.{{HOMEPAGE_VAR_DOMAIN}}
        description: Indexer manager
        server: my-docker
        container: prowlarr
    - LazyLibrarian:
        icon: lazylibrarian
        href: https://lazylibrarian.{{HOMEPAGE_VAR_DOMAIN}}
        description: Book automation
        server: my-docker
        container: lazylibrarian

    - Gluetun:
        icon: gluetun
        description: VPN tunnel
        server: my-docker
        container: gluetun

- Core:
    - Pi-hole:
        icon: pi-hole
        href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin/
        description: DNS
        server: my-docker
        container: pihole
    - Caddy:
        icon: caddy
        description: Reverse proxy
        server: my-docker
        container: caddy

- Security:
    - Authelia:
        icon: authelia
        href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
        description: SSO
        server: my-docker
        container: authelia
