- Apps:
    - Photos:
        icon: immich
        href: https://photos.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: Immich
        server: my-docker
        container: immich-server
    - Recipes:
        icon: mealie
        href: https://recipes.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: Mealie
        server: my-docker
        container: mealie
    - Books:
        icon: calibre-web-automated
        href: https://reader.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: calibre-web-automated
        server: my-docker
        container: calibre-web-automated

- Core:
    - DNS:
        icon: pi-hole
        href: https://dns.{{HOMEPAGE_VAR_DOMAIN}}/admin/
        subtitle: Pi-hole
        server: my-docker
        container: pihole
    - Proxy:
        icon: caddy
        subtitle: Caddy
        server: my-docker
        container: caddy
    - Authentication:
        icon: authelia
        href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: Authelia
        server: my-docker
        container: authelia

- Media Automation:
    - Indexer:
        icon: prowlarr
        href: https://indexer.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: Prowlarr
        server: my-docker
        container: prowlarr
    - VPN:
        icon: gluetun
        subtitle: Gluetun
        server: my-docker
        container: gluetun
    - Downloads:
        icon: qbittorrent
        href: https://downloads.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: qBittorrent
        server: my-docker
        container: qbittorrent
    - Book Management:
        icon: shelfmark
        href: https://books.{{HOMEPAGE_VAR_DOMAIN}}
        subtitle: Shelfmark
        server: my-docker
        container: shelfmark
